// OFFLINE corpus replay. Reads bench/corpus/fixtures/<id>/{before,after}.rs +
// meta.json and asserts: the detector FIRES on the pre-fix file (within the
// patched region) and is SILENT on the post-fix file. No network, no git.
// Exit 0 iff every entry passes. Also emitted as bench/corpus/BENCHMARK.md.
import * as fs from 'fs';
import * as path from 'path';
import { runScan, ScanInput } from '../../src/engine';
import { FileDiff } from '../../src/types';
import { defaultConfig } from '../../src/config';

function findRoot(): string {
  let dir = __dirname;
  for (let i = 0; i < 8; i++) {
    if (fs.existsSync(path.join(dir, 'bench', 'corpus', 'manifest.json'))) return dir;
    dir = path.dirname(dir);
  }
  return process.cwd();
}

interface Meta {
  id: string;
  rule: string;
  repo: string;
  sha: string;
  file: string;
  expectTier: number;
  note: string;
  buggyChanged: number[];
  fixedChanged: number[];
}

function syntheticDiff(file: string, changed: number[]): FileDiff {
  return {
    newPath: file,
    oldPath: file,
    status: 'modified',
    changedLines: new Set(changed),
    removedLines: new Set(),
    hunks: [],
    binary: false,
  };
}

function input(file: string, text: string, changed: number[]): ScanInput {
  return {
    files: [{ diff: syntheticDiff(file, changed), headText: text, baseText: null }],
    context: { source: 'patch' },
  };
}

interface Row {
  id: string;
  rule: string;
  fires: boolean;
  fireLine: number | null;
  silent: boolean;
  pass: boolean;
  detail: string;
}

async function main() {
  const root = findRoot();
  const fixturesDir = path.join(root, 'bench', 'corpus', 'fixtures');
  const manifest = JSON.parse(
    fs.readFileSync(path.join(root, 'bench', 'corpus', 'manifest.json'), 'utf8')
  );
  if (!fs.existsSync(fixturesDir)) {
    console.error(
      'No fixtures found. Run `node dist/scripts/build-fixtures.js` once (network) to generate them.'
    );
    process.exit(2);
  }

  const rows: Row[] = [];
  for (const e of manifest.entries) {
    const dir = path.join(fixturesDir, e.id);
    const metaPath = path.join(dir, 'meta.json');
    if (!fs.existsSync(metaPath)) {
      rows.push({
        id: e.id,
        rule: e.rule,
        fires: false,
        fireLine: null,
        silent: false,
        pass: false,
        detail: 'MISSING FIXTURE (run build-fixtures)',
      });
      continue;
    }
    const meta: Meta = JSON.parse(fs.readFileSync(metaPath, 'utf8'));
    const before = fs.readFileSync(path.join(dir, 'before.rs'), 'utf8');
    const after = fs.readFileSync(path.join(dir, 'after.rs'), 'utf8');
    const cfg = defaultConfig();

    const buggy = await runScan(input(meta.file, before, meta.buggyChanged), {
      config: cfg,
      ruleFilter: [meta.rule],
      includeTests: true,
    });
    const fixed = await runScan(input(meta.file, after, meta.fixedChanged), {
      config: cfg,
      ruleFilter: [meta.rule],
      includeTests: true,
    });

    const lo = Math.min(...meta.buggyChanged);
    const hi = Math.max(...meta.buggyChanged);
    const hit = buggy.findings.find(
      (f) => f.ruleId === meta.rule && f.line >= lo - 2 && f.line <= hi + 2
    );
    const fires = !!hit;
    const silent = fixed.findings.filter((f) => f.ruleId === meta.rule).length === 0;
    const pass = fires && silent;
    rows.push({
      id: e.id,
      rule: e.rule,
      fires,
      fireLine: hit ? hit.line : null,
      silent,
      pass,
      detail: pass
        ? `fires @${meta.file}:${hit!.line}, silent on fix`
        : `${fires ? '' : 'DID NOT FIRE on buggy; '}${silent ? '' : 'FIRED on fixed'}`,
    });
  }

  // Render table.
  const w = { id: 24, rule: 26 };
  const header = `${'id'.padEnd(w.id)} ${'rule'.padEnd(w.rule)} fire  silent  verdict`;
  console.log(header);
  console.log('-'.repeat(header.length));
  const mdLines: string[] = [
    '# Corpus replay (BENCHMARK.md)',
    '',
    'Auto-generated by `npm run corpus`. Each detector must fire on the pre-fix',
    'file (within the patched region) and stay silent on the post-fix file. Runs',
    'fully offline from `bench/corpus/fixtures/`.',
    '',
    '| id | rule | fires on buggy | silent on fixed | verdict |',
    '| --- | --- | --- | --- | --- |',
  ];
  let passN = 0;
  for (const r of rows) {
    console.log(
      `${r.id.padEnd(w.id)} ${r.rule.padEnd(w.rule)} ${(r.fires ? 'YES' : 'no ').padEnd(4)}  ${(r.silent ? 'YES' : 'no ').padEnd(6)}  ${r.pass ? 'PASS' : 'FAIL — ' + r.detail}`
    );
    mdLines.push(
      `| ${r.id} | \`${r.rule}\` | ${r.fires ? '✅' + (r.fireLine ? ` (L${r.fireLine})` : '') : '❌'} | ${r.silent ? '✅' : '❌'} | ${r.pass ? '**PASS**' : '**FAIL**'} |`
    );
    if (r.pass) passN++;
  }
  const summary = `\n${passN}/${rows.length} entries pass.`;
  console.log(summary);
  mdLines.push('', `**${passN}/${rows.length} entries pass.**`, '');

  const outMd = path.join(root, 'bench', 'corpus', 'BENCHMARK.md');
  fs.writeFileSync(outMd, mdLines.join('\n'));

  if (passN !== rows.length) process.exit(1);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
